version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: desafio_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: desafio_tecnico
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: desafio_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:admin@postgres:5432/desafio_tecnico"
    ports:
      - '3000:3000'

volumes:
  pgdata:
