services:
  backend:
    container_name: desafio_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/desafio_tecnico
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: desafio_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: desafio_tecnico
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
